[package]
name = "rust-markdown"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.14.0"
walkdir = "2.3.2"
